var data = {
    "english": {
        "lang": "Language",
        "list": "List of patient",
        "add": "Add patients",
        "ID": "Patient ID",
        "fname": "Fisrt Name",
        "lname": "Last Name",
        "dateofbirth": "Date of birth",
        "gender": "Gender",
        "phone": "Phone Number",
        "email": "Email",
        "height": "Height",
        "weight": "Weight",
        "blood": "Blood Group",
        "creat": "Create On",
        "mod": "Modified On",
        "view": "View Detail",
        "edit": "Edit",
        "delete": "Delete"
    },
    "vietnamese": {
        "lang": "Ngôn ngữ",
        "ID": "Mã bệnh nhân",
        "lname": "Tên",
        "fname": "Họ",
        "dateofbirth": "Ngày sinh",
        "gender": "giới tính",
        "phone": "Số điện thoại",
        "email": "Email",
        "height": "Chiều cao",
        "weight": "Cân nặng",
        "blood": "Nhóm máu",
        "creat": "Ngày lập sổ",
        "mod": "Ngày cập nhật",
        "view": "Xem chi tiết",
        "edit": "Sửa",
        "delete": "Xóa",
    },
    "japanese": {
        "lang": "日本語",
        "list": "患者一覧",
        "add": "患者追加",
        "ID": "患者 ID",
        "fname": "名字",
        "lname": "名前",
        "dateofbirth": "生年月日",
        "gender": "性別",
        "phone": "電話番号",
        "email": "Email",
        "height": "身長",
        "weight": "体重",
        "blood": "血液型",
        "creat": "作成日",
        "mod": "変更日",
        "view": "詳細を表示",
        "edit": "編集",
        "delete": "削除"
    }
}